### PR TITLE
Master running on rkt

### PR DESCRIPTION
**Pull request by sjpotter**
take 3

### CODE REVIEW

**Comment by yifan-gu** [comment]
I am going to rebase this atop the current HEAD of the gce_coreos_rkt. Then run e2e tests.

**Comment by sjpotter** [comment]
what I should note, this takes a very long time for master to come up between rkt overhead and docker2aci overhead, the cluster comes up, but longer than the normal -up wants to wait

**Comment by yifan-gu** [comment]
ok, this assumes docker2aci is in the tar, right?

**Comment by sjpotter** [comment]
yes, I updated your volume-lock tarball

**Comment by yifan-gu** [comment]
@sjpotter KK, I uploaded another tarbal as well :)

**Pull request merged**
